agent_name: selling_agent_1
author: bosch
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  libp2p_node.log: QmZaCqrVm8RUM3aQkgGnjCEgu8jHEqdEL7k9piRoha7f8V
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.20.0
- fetchai/p2p_libp2p:0.26.0
contracts:
- bosch/service_directory:0.1.0
protocols:
- fetchai/acn:1.1.0
- fetchai/contract_api:1.1.0
- fetchai/default:1.1.0
- fetchai/fipa:1.1.0
- fetchai/ledger_api:1.1.0
- fetchai/signing:1.1.0
- fetchai/state_update:1.1.0
skills:
- bosch/fipa_negotiation:0.1.0
default_connection: fetchai/p2p_libp2p:0.26.0
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing:
  fetchai/ledger_api:1.1.0: fetchai/ledger:0.20.0
connection_private_key_paths:
  fetchai: fetchai_private_key.txt
private_key_paths:
  ethereum: ethereum_private_key.txt
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  aea-ledger-fetchai: {}
---
public_id: fetchai/p2p_libp2p:0.26.0
type: connection
config:
  delegate_uri: 127.0.0.1:11000
  entry_peers: []
  local_uri: 127.0.0.1:9000
  public_uri: 127.0.0.1:9000
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2022-01-01'
  not_before: '2021-01-01'
  public_key: fetchai
  save_path: .certs/conn_cert.txt
